names=["Art Carney",
"Akemi Darenogare",
"Billy Bob Thornton",
"Bill Daley",
"Amanda Bynes",
"Anna Friel",
"Alexander Skarsgard",
"Anna Faris",
"Bill Pullman",
"Anjelica Huston",
"Angela Bassett",
"Alx James",
"Benjamin Bratt",
"Andy Garcia",
"Bernie Mac",
"Andreea Diaconu",
"Anna Kendrick",
"Anna Sui",
"Barry Pepper",
"Alexis Thorpe",
"Ashley Judd",
"Amy Ryan",
"Analeigh Tipton",
"Anne Hathaway",
"Amanda Peet",
"Amanda Crew",
"Adriana Barraza",
"Ashton Kutcher",
"Ali Larter",
"Arnold Schwarzenegger",
"Amy Adams",
"Berenice Bejo",
"Alessandra Ambrosio",
"Audrey Hepburn",
"Andy Samberg",
"Abigail Breslin",
"Aaron Judge",
"Andrew Luck",
"Bill Murray",
"Anna Paquin",
"Angelina Jolie",
"Barbra Streisand",
"Ashley Graham",
"Anthony Mackie",
"Alec Baldwin",
"Andy Murray",
"Armin Mueller-Stahl",
"Aaron Paul",
"Andrew Lincoln",
"Adrianne Palicki",
"Alice Eve",
"Anne Bancroft",
"Adrien Brody",
"Anne Baxter",
"Benedict Cumberbatch",
"Andie MacDowell",
"Alexandra Daddario",
"Ben Stiller",
"Andrew Garfield",
"Amy Schumer",
"Ben Kingsley",
"Benicio Del Toro",
"bella thorne",
"Ben Foster",
"Andy Serkis",
"Ashley Greene",
"Albert Finney",
"Alan Rickman",
"Bill Rancic",
"Barabara Palvin",
"Ben Affleck",
"Adriana Lima",
"Albert Brooks",
"Bill Paxton",
"Alan Arkin",
"Anthony Hopkins",
"Alex Pettyfer",
"Amber Heard",
"Amanda Seyfried",
"Annette Bening",
"Antonio Banderas",
"Anthony Perkins",
"Alicia Vikander",
"Aaron Taylor-Johnson",
"Al Roker",
"AnnaSophia Robb",
"Anderson Cooper",
"Audrey Tautou",
"Betty White",
"Bella Hadid",
"Adam Sandler",
"Alan Alda",
"Beyonce Knowles",
"Al Pacino",
"Bill O Reilly",
"Bill Hader",
"Ben Johnson",
"Ava Gardner",
"Adele",
"Bette Midler",]

name_ind = {name: index for index, name in enumerate(names)}
name_strind = {name: str(index) for index, name in enumerate(names)}

bads = {"95",
"106",
"1495",
"1210",
"1055",}